# Generated by Django 5.2.4 on 2025-09-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_userintent_conversation_chatturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
