# Generated by Django 5.2.4 on 2025-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='https://www.svgrepo.com/show/452030/avatar-default.svg', null=True, upload_to='avatars/'),
        ),
    ]
