# Generated by Django 5.2.4 on 2025-08-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawdocument',
            old_name='expired_date',
            new_name='updated_date',
        ),
    ]
