# Generated by Django 5.2.4 on 2025-08-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0002_rename_expired_date_lawdocument_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawdocument',
            name='effective_date',
        ),
        migrations.AddField(
            model_name='lawdocument',
            name='applied_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lawdocument',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
