# Generated by Django 5.2.4 on 2025-08-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0003_remove_lawdocument_effective_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawdocument',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
