# Generated by Django 5.2.4 on 2025-08-20 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0004_lawdocument_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawdocument',
            name='pdf_url',
        ),
        migrations.CreateModel(
            name='LawDocumentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('signer', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_status', models.CharField(blank=True, max_length=100, null=True)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='laws.lawdocument')),
            ],
        ),
    ]
