# Generated by Django 5.2.4 on 2025-08-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0005_remove_lawdocument_pdf_url_lawdocumentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalnews',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='legalnews',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalnews',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
