# Generated by Django 5.2.4 on 2025-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0006_alter_legalnews_content_alter_legalnews_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
