# Generated by Django 5.2.4 on 2025-08-26 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0007_lawcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalnews',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='laws.lawcategory'),
        ),
    ]
