# Generated by Django 5.2.4 on 2025-09-02 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0008_legalnews_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalNewsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('content_md', models.TextField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='laws.legalnews')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
