# Generated by Django 5.2.4 on 2025-09-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0009_legalnewsdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawdocument',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
