# Generated by Django 5.2.4 on 2025-09-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0010_alter_lawdocument_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=20, unique=True)),
                ('question_title', models.CharField(max_length=500)),
                ('question_url', models.URLField(max_length=1000)),
                ('asked_date', models.DateField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laws.lawcategory')),
            ],
            options={
                'ordering': ['-asked_date'],
            },
        ),
    ]
