# Generated by Django 5.2.4 on 2025-09-19 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0011_legalconsultation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legalconsultation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='legalconsultation',
            name='asked_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='legalconsultation',
            name='question_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='legalconsultation',
            name='question_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
